version: "3.8"

networks:
  orbitdb:
    driver: bridge

services:
  node:
    build: .
    container_name: orbitdb-node-${HOSTNAME}  # Unique container name per device
    networks:
      orbitdb:
    ports:
      - "4001:4001"  # IPFS swarm
      - "4002:4002"  # OrbitDB
      - "4003:4003"  # Libp2p
    volumes:
      - ./ipfs-data:/app/ipfs
      - ./orbitdb-data:/app/orbitdb
    environment:
      - BOOTSTRAP_PEERS=/ip4/192.168.1.100/tcp/4001/p2p/QmBootstrapPeer
    command: node node.js
